### PR TITLE
Fix GH-546: Update faq language

### LINKED ISSUE #546: Update Support/ Compatibility Information on Scratch FAQ Page
Re case (removed), the information for what software we support on the FAQ page needs to be updated to reflect the browser info and AIR/ offline editor info.

FAQ Page: https://scratch.mit.edu/info/faq/

I'm not really sure who would want to write the copy for this... maybe @kaschm would know? (If not, feel free to direct me to someone else.) : )

EDIT: removed links to private repositories.

### PR DESCRIPTION
**Pull request by mewtaylor**
Fixes #546

### CODE REVIEW

**Comment by kaschm** [comment]
:+1: LGTM

**Comment by jwzimmer** [comment]
Testing
@mewtaylor @kaschm 
- Very minor:
what's our opinion on Oxford commas?
screen shot 2016-08-24 at 3 46 49 pm
screen shot 2016-08-24 at 3 46 39 pm
- This last line isn't in @kaschm's copy:
screen shot 2016-08-24 at 3 50 15 pm
screen shot 2016-08-24 at 3 50 05 pm
- And just to verify, what the downloadable part should say since the copy for that wasn't as specific, @kaschm can you ok this content:
screen shot 2016-08-24 at 3 52 42 pm

**Comment by kaschm** [comment]
1) Yes to oxford commas! Please add it in there.

2) I'm ok with keeping the line in there about 1.4

3) ok on this content as well.

**Comment by jwzimmer** [comment]
@mewtaylor can you add the comma in that first line, do you have time to do that before tomorrow?

**Comment by mewtaylor** [comment]
Just added :) https://github.com/LLK/scratch-www/commit/ab6f8e1049d7c912d3cbb34c6b3cfd287553c516

**Comment by jwzimmer** [comment]
Oxford comma is now present:
screen shot 2016-08-24 at 4 47 06 pm

**Pull request merged**
