### PR TITLE
[Master] Release Scratch 3.0!

### PR DESCRIPTION
**Pull request by rschamp**
OMG OMG OMG

### CODE REVIEW

**Comment by paulkaplan** [comment]
👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇 👍 💯 🥇

**Comment by mewtaylor** [comment]
confetti-horn-emoji

**Comment by WorldLanguages** [comment]
GG

**Comment by kerrtrvs** [comment]
Ayyy! 🎉

**Comment by MasterOfTheTiger** [comment]
Can't wait! I am very much for this update. A lot of the Scratch community is very excited.

**Comment by apple502j** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Kenny2github** [comment]
image

**Comment by colbygk** [comment]
nomoreflash

**Comment by rschamp** [comment]
The release! https://travis-ci.org/LLK/scratch-www/jobs/474385840

**Pull request merged**
