### PR TITLE
Fix text overflow in what's happening

### LINKED ISSUE #4023: Text overflow in what's happening
Related to #2853
When there is a long text in what's happening, the text does not break.
image

### Steps to Reproduce

1. On your alt account, follow your main.
2. Switch to your main.
3. Create and name a project:
————————————————————————————————————————————————————————————————————————————————————————————————————
4. Love and/or favorite it.
5. Switch to your alt account and go to the front page.

### Operating System and Browser

Windows NT 10.0, Chrome 83.0.4103.61

### PR DESCRIPTION
**Pull request by BoomerScratch**
### Resolves:

Resolves #4023

### Changes:

Adds `overflow-wrap: anywhere` to fix text overflow (in "what's happening"). I'm not sure if it works on all browsers. If it does not, please tell me a fix.

### Test Coverage:

Manually tested with inspect.
\
\
\
@benjiwheeler

### CODE REVIEW

**Comment by apple502j** [comment]
Well, it doesn't work on Safari:
See also: https://caniuse.com/#feat=mdn-css_properties_overflow-wrap_anywhere

**Comment by BoomerScratch** [comment]
@apple502j Do you know a fix?

**Comment by mxmou** [comment]
> @apple502j Do you know a fix?

`word-break: break-word`? Deprecated but should work.

**Comment by BoomerScratch** [comment]
@mxmou Ok, I will add it... (I will not remove the other one, just in case)

**Comment by benjiwheeler** [comment]
I think including both is the right move. Thanks @BoomerScratch

**Pull request merged**
