### PR TITLE
Fix gh-366: Homepage - Failed PropType

### LINKED ISSUE #366: On homepage: "Failed propType: Invalid prop `projectCount` of type `string` supplied to `Intro`, expected `number`."
I get this when running locally.

### PR DESCRIPTION
**Pull request by TheGrits**
This should fix #366 
@mewtaylor @rschamp

### CODE REVIEW

**Comment by mewtaylor** [comment]
@TheGrits I'm getting an issue in the other direction with that change (when the number is retrieved it throws an error that it's not a string). I think the solution here might be to remove the `propTypes` validator for this value altogether

**Comment by TheGrits** [comment]
@mewtaylor 
Makes sense, I have made the change. 
I don't seem to be getting any more errors regarding the change, so we should be good to go.

**Comment by mewtaylor** [comment]
sweet! I'll take a look this afternoon!

**Comment by rschamp** [comment]
I think needing to remove the validation hints at an issue with the original solution. We expect the count to be a number, since we call `toLocaleString` on the value — it doesn't work on strings.  Could we change it to instead display the "over X" text only if the value is unchanged from its default? Then we'll fix this bug as well as the localization issue at once.

The text that contains the count is also not localized, but that is a different issue.

**Comment by mewtaylor** [comment]
@rschamp that sounds great to me! +1 on localization too, but I can open up a separate issue for that like you mentioned – there are few places, upon inspection, where we have default text that's not localized.

**Comment by TheGrits** [comment]
@mewtaylor So what do you need me to do? I'm a little confused.

**Comment by mewtaylor** [comment]
@rschamp correct me if I'm misunderstanding but:

@TheGrits I think the idea would be to leave the default as a number in `splash.jsx`, and rather than remove the `propType` check in `intro.jsx`, instead add a conditional check that would see if the value for `this.props.projectCount` is equal to `this.getDefaultProps().projectCount` in the `render()` method of `intro.jsx`. If they are equal (so we're using the default value), then we'd render `'over 13 million'` rather than `this.props.projectCount.toLocaleString()`. This could be done by assigning a variable in `render()` to `'over 13 million'` or `<number>.toLocaleString()` ahead of the `return` statement. Does that help?

**Comment by rschamp** [comment]
@mewtaylor Pretty much what I was thinking. I think we might want to keep the two strings "A creative learning community with `X` projects shared" and "A creative learning community with over 13 million projects shared" separate for localization purposes, rather than just having `X` be a number or `over 13 million`.  The grammar isn't necessarily going to be the same for those two statements.

**Comment by TheGrits** [comment]
@mewtaylor Makes a lot more sense, thanks. :+1: 
@rschamp Sounds good.

**Comment by mewtaylor** [comment]
@TheGrits @rschamp #356 was fixed in a different way by https://github.com/LLK/scratch-www/pull/390, so I'm gonna close this.

**Pull request closed without merging**
