### PR TITLE
[Develop] Hotfix: Remove `phoneLength` validation

### PR DESCRIPTION
**Pull request by mewtaylor**
See #826

### CODE REVIEW

**Comment by rschamp** [comment]
Could you explain why this works differently than master? Why won't this just skip validation if the user's phone number is just `+`?

**Comment by mewtaylor** [comment]
I was wrong, it was the same issue as on `master` – fixed now, thanks!

**Comment by TheGrits** [comment]
What if you were to validate all phone numbers according to a global minimum length, and only allow numbers and `+` in the field?

**Comment by mewtaylor** [comment]
@TheGrits you're absolutely right – and I think this fix will do just that. It won't allow a submission without any numbers present, meaning there is a global minimum length (with some validation of phone number structure by country still being done in the `isPhone` check).

**Comment by TheGrits** [comment]
@mewtaylor Ah ok, that makes sense.

**Pull request merged**
