### PR TITLE
Fix gh-918: Update Video Link

### PR DESCRIPTION
**Pull request by TheGrits**
As per @sleggss on #918

(@mewtaylor I see that the issue was assigned to you, but I assumed that it would be OK for me to fix it because of the `help wanted` tag)

### CODE REVIEW

**Comment by mewtaylor** [comment]
@rschamp – wondering if we should add in the lint exception for links, like in this example. Thoughts?

**Comment by TheGrits** [comment]
@mewtaylor We had a similar problem here on the guidelines page: [line 33](https://github.com/LLK/scratch-www/blob/develop/src/views/guidelines/guidelines.jsx#L33)

**Comment by TheGrits** [comment]
@mewtaylor I pushed a fix for the lint error, Travis is passing now.

**Comment by mewtaylor** [comment]
Cool thanks @TheGrits !

**Comment by jwzimmer** [comment]
### Testing

Looks good in Chrome Version 53.0.2785.116 (64-bit), Mac OS X El Capitan, and Firefox 49.0.1 on Win 7 VM. 
Link & Text are changed to match as described in https://github.com/LLK/scratch-www/issues/918.

**Pull request merged**
