### PR TITLE
Add redirects for Animate a Character and Video Sensing Tutorials

### LINKED ISSUE #4203: Add redirect shortcuts for 2 tutorials: Animate a Character & Video Sensing
We often want to share links to tutorials in resources as short URLs. There are shortcuts for most of the top tutorials, except for Animate a Character and Video Sensing

SHORTCUTS:
For Animate a Character
**scratch.mit.edu/animate-a-character**

For Video Sensing:
 **scratch.mit.edu/video-sensing**

### PR DESCRIPTION
**Pull request by Accio1**
### Resolves:

Resolves #4203 

### Changes:

This Pull Request adds redirects for the [Animate a Character](https://scratch.mit.edu/projects/editor/?tutorial=animate-a-character) and [Video Sensing](https://scratch.mit.edu/projects/editor/?tutorial=video-sensing) tutorials. https://scratch.mit.edu/animate-a-character will redirect to the Animate a Character tutorial, and https://scratch.mit.edu/video-sensing will redirect to the Video Sensing tutorial.

### CODE REVIEW

**Comment by Accio1** [comment]
@benjiwheeler

**Comment by SausageMcSauce** [comment]
You seem to have misspelled 'character' in the redirect name, maybe you could fix that?

**Comment by Accio1** [comment]
> You seem to have misspelled 'character' in the redirect name, maybe you could fix that?

Fixed! Thanks!

**Comment by benjiwheeler** [comment]
This looks good to me at first glance -- I'll test it soon so we can merge it! It's currently scheduled to be tested in September.

**Comment by rschamp** [comment]
(I'm holding off merging this today to avoid interfering with staging)

**Pull request merged**
