### PR TITLE
Fix gh-1899: Create Console Warning

### PR DESCRIPTION
**Pull request by JoelGritter**
### Changes:

Created new component for the console warning. The console warning has localized strings in the general l10n.json file, and uses console.log() to write to the console. (console.log() is currently not permitted in the lint rules, so this may need to be changed)

The resulting console warning should look like this:
image

### CODE REVIEW

**Comment by apple502j** [comment]
The code does nothing.

**Comment by JoelGritter** [comment]
@apple502j You're right, it does nothing; but that is purposeful. It doesn't do anything because the component isn't being used elsewhere yet.

**Comment by JoelGritter** [comment]
@rschamp @thisandagain suggested using a component: https://github.com/LLK/scratch-www/issues/1899#issuecomment-392913936

**Comment by JoelGritter** [comment]
Closing for restructuring of solution.

**Pull request closed without merging**
