### PR TITLE
CE-294 Fix(7137) Make the love and favorite icons colorblind friendly 

### PR DESCRIPTION
**Pull request by edelfino11**
Resolves: 

This fix solves issue [7137](https://github.com/LLK/scratch-www/issues/7137), simply changed the love and favorite svgs to the colorblind friendly svg on the stats.scss

Passing all tests: 
Screen Shot 2022-12-01 at 12 41 28 PM

### CODE REVIEW

**Review by DNin01 — CHANGES_REQUESTED** [review]
It looks like the activated love button was changed to an outlined favorite icon. You can see that the second part you changed is under `.project-loves.loved {` which refers to the love icon when you loved a project, so that should stay what it was before. `background-image: url("/svgs/favorite/favorite_type-gray.svg");` should be below `.project-favorites {` instead of `.project-loves.loved {`.

Minor detail, these outlined icons are shaped slightly differently than the filled-in icons:
 
It might look more consistent if instead of changing what image is used, you modified the grayed-out icons ([`love-gray.svg`](https://github.com/LLK/scratch-www/blob/develop/static/svgs/project/love-gray.svg) and [`fav-gray.svg`](https://github.com/LLK/scratch-www/blob/develop/static/svgs/project/fav-gray.svg)) to have an outline using an SVG editor.

**Comment by edelfino11** [comment]
Oh, I did not realize the subtle difference! I completely changed the SVGs and fixed the small mistake I had before, sorry about that.

**Review by DNin01 — APPROVED** [review]
Looks great!

**Comment by benjiwheeler** [comment]
@edelfino11, this change looked great! Our design team took a look and made some tiny tweaks, and made the outline gray a little darker (and changed the remix and views icons too). Thanks for collaborating on this with us!

**Comment by DNin01** [comment]
👏

**Comment by Racecar-Roaster** [comment]
This is really cool and a nice feature! But I think it could be better if you make it just the thick outline so it's more colorblind friendly!

**Pull request merged**
