### PR TITLE
[master]Release/2020 08 20

### PR DESCRIPTION
**Pull request by picklesrus**
Release Notes:
Bug fixes

- Touching color works better with the pixelate effect (thanks @adroitwhiz!):
https://github.com/LLK/scratch-render/issues/573

- Touching color works better with color and brightness effects (thanks @adroitwhiz!)
https://github.com/LLK/scratch-render/issues/578

- Dragging sprite tiles in RTL to reorder them is less broken (thanks @noamraph!)
https://github.com/LLK/scratch-gui/issues/6020

- Fixed issues with outlines showing the incorrect width when one of the gradient colors is transparent
- Use ... instead of truncating strings on project titles in carousels (thanks @R4356th!)

### CODE REVIEW

**Comment by apple502j** [comment]
Is gradient outlines released intentionally, or is it supposed to be released this week?

**Comment by picklesrus** [comment]
Gradient outlines were part of a previous release. There are some related bug fixes in this release. Just added release notes.

**Comment by apple502j** [comment]
@picklesrus #4271 is still open...

**Comment by picklesrus** [comment]
@apple502j Yep! Thanks for pointing that out.  I'm not sure if that branch is being used for any testing/bug fixes so I'll leave it open and let @fsih close it when ready.

**Pull request merged**
