### PR TITLE
CE-319: Add cookie policy page

### PR DESCRIPTION
**Pull request by corihudson**
This PR adds a cookie policy page, linked to by #7412. This PR should not be merged until that PR and CE-334 are ready. 
### Resolves:

- CE-319

### Changes:

- Adds a `/cookies` page and links it in the footer
- Replaces TED talk embed with thumbnail link to video, removing advertising cookie

### CODE REVIEW

**Comment by 8-6-7-5-3-0-9-1-9-8-5-0-5-1-5-2-0-6-0-7** [comment]
@corihudson What about GA cookies, will it mention those? Also could it be possible to support DNT?

**Comment by corihudson** [comment]
@8-6-7-5-3-0-9-1-9-8-5-0-5-1-5-2-0-6-0-7 hey there! this PR does include documentation of Google Analytics cookies, but DNT support is not in the scope of this ticket.

**Review by tomlum — APPROVED** [review]
Looks good!

**Review by chrisgarrity — APPROVED** [review]
Looks good! Thank you

**Pull request merged**
