### PR TITLE
Fix gh-1248: Migrate Parents Page

### LINKED ISSUE #1248: Migrate Parents Page

### PR DESCRIPTION
**Pull request by TheGrits**
Eventually will resolve #1248 

I haven't actually gotten the chance to test locally yet, I'm up to my ears in school and an internship at the same time. 😅 iirc I used the educators page as a template so there shouldn't be too many problems. Just thought I would keep this one on the radar for both me and y'all at the Media Lab, so that we can get this one to production (hopefully) in the July release.

I actually don't remember doing this, but it looks like I based this branch off of #1272 (So I guess this one could be merged and then the other PR can be closed)

## Test cases:
- should have the same content as the current parents page
- should look similar to the educators page
- localization should work (but probably won't because I doubt the strings are in the translation database yet)

### CODE REVIEW

**Comment by TheGrits** [comment]
@mewtaylor I'm going to do a rebase at some point to resolve the conflict.

**Comment by mewtaylor** [comment]
Also @TheGrits is this still `in-progress`, or will it be ready for review once the conflicts are resolved?

**Comment by TheGrits** [comment]
@mewtaylor I will likely need to make changes, I haven't gotten the chance to test it locally yet. I'm working my tail off this summer lol

**Comment by mewtaylor** [comment]
@TheGrits lol yeah you've been doing lots of PRs! No worries if you need to make changes, and definitely take your time (and some time off if you wanna!), there's no rush on this one :).

**Comment by TheGrits** [comment]
@mewtaylor I wasn't meaning PRs, I'm working my tail off IRL. 😝 Maybe this weekend I'll do a reboot of the PR, depends if I need to work on Saturday or not.

**Comment by mewtaylor** [comment]
@TheGrits oh lol well you've been somehow able to still submit fixes during that time, which is amazing 😺

**Comment by TheGrits** [comment]
@mewtaylor I might be able to test it locally tonight, I didn't end up having work today. 😎

**Comment by TheGrits** [comment]
@mewtaylor How do you get the translations to work? I have a local instance up and running but the translations aren't being filled in:
screen shot 2017-08-08 at 3 19 53 pm

**Comment by mewtaylor** [comment]
@TheGrits have you run the command `make translations` yet? That would be necessary to start seeing them, assuming you have the `l10n.json` file in the right place.

**Comment by St19Galla** [comment]
@TheGrits This also was an issue for me when making the Down Deep page. I just replaced the `FormattedMessage` with the actual text for the screenshots of the local instance then re-replaced them when creating the PR :)

**Comment by TheGrits** [comment]
@mewtaylor Nope, I wasn't aware of that command before. Thanks!

**Comment by thisandagain** [comment]
@TheGrits Did you mean to close this?

**Comment by TheGrits** [comment]
@thisandagain Yep, I'm doing a rebase to resolve the conflicts. Thanks for the reminder!

**Pull request closed without merging**
