### PR TITLE
Update compatibility requirements to clarify support for ChromeOS

### PR DESCRIPTION
**Pull request by thisandagain**
- Clarify support for ChromeOS
- List platforms in order of use from most to least (Windows, ChromeOS, MacOS, Linux)
- Remove confusing line about Chromium
- Remove "Windows" from Safari listing as it is no longer supported

### CODE REVIEW

**Comment by mewtaylor** [comment]
@thisandagain do we need to hotfix this, or should it go in with the release?

Also does anyone else read that branch name as sounding like "oreos" in their head, but with "chrome"? Like the most delicious browser cookie snack there ever was?

**Comment by thisandagain** [comment]
@mewtaylor I'd be fine with either but I would like it to get out this week. Would you like me to target the PR against the release branch?

**Comment by mewtaylor** [comment]
@thisandagain if there's a time sensitivity on it I'm fine with having it be a hotfix! Would you mind opening a second PR against the release branch too, so we can just sanity check it on staging/so it goes into staging too?

**Comment by thisandagain** [comment]
Looks good in staging:
https://scratch.ly/info/faq

**Pull request merged**
