### PR TITLE
Fix gh-1026: Trust and Safety Manager URL update

### LINKED ISSUE #1026: Link for Trust & Safety Manager on Jobs page
As discussed with @mewtaylor, on the jobs page on Staging, we updated the jobs available in https://github.com/LLK/scratch-www/pull/989 (which is in the **November 14** milestone) but it looks like the link for the trust & safety manager  position will still not work.

### PR DESCRIPTION
**Pull request by TheGrits**
Should fix #1026 

I have a feeling Travis won't like how long the URL is though...

### CODE REVIEW

**Comment by jwzimmer** [comment]
@mewtaylor if the URL is rejected for making the line too long, could @TheGrits use bitly to shorten the link? The old link for the Community Manager position was a bitly link...

**Comment by jwzimmer** [comment]
@TheGrits I think you can go ahead and try with this shortened URL: http://bit.ly/2f5hABE so it will pass the check, and we'll see if @mewtaylor knows of any reason that isn't a good idea when the PR is reviewed. : )

**Comment by TheGrits** [comment]
@jwzimmer Thanks, I pushed the change!

**Comment by jwzimmer** [comment]
Thanks @TheGrits!

**Comment by mewtaylor** [comment]
bitly is fine – @rschamp did we decide at some point to exempt urls from linting?

**Comment by rschamp** [comment]
I believe they will be when we switch over to eslint-config-scratch.

**Comment by mewtaylor** [comment]
@jwzimmer @thisandagain @rschamp I'd like to cherry pick this into our release tomorrow, since currently people cannot apply for the position through Scratch – thoughts?

**Comment by thisandagain** [comment]
Agreed. Thanks @mewtaylor

**Pull request merged**
