### PR TITLE
Gh 1751/add abkhaz to languages menu

### PR DESCRIPTION
**Pull request by LiFaytheGoblin**
### Resolves: #1751 
added Abkhaz to languages.json

### Test Coverage:
I tested it in firefox and also run the tests. It sais there was just a formatting problem in a file I didn't even touch so I guess that might be okay.

I somehow found three older commits on my computer only and I couldn't remove them. I tried updating the repository but it didn't overwrite the commits. Apparently, by the commits, nothing was changed, except for I removed and then added back an empty line to the credits.jsx file. Weird.

### CODE REVIEW

**Comment by amazinigmech2418** [comment]
For some reason, there are 88 warnings on Travis... @LiFaytheGoblin Also, they are in files that weren't even changed. Maybe there were build errors before this PR.

**Comment by Kenny2github** [comment]
@amazinigmech2418 there's always a lot of warnings, it's the errors that are important

**Comment by amazinigmech2418** [comment]
OK. @Kenny2github

**Comment by LiFaytheGoblin** [comment]
Huh why have the checks failed :(

**Comment by vutondesign** [comment]
I seem to be having a similar problem over at llk/scratch-gui#1265

**Comment by amazinigmech2418** [comment]
@LiFaytheGoblin The checks failed from the warnings.

**Comment by St19Galla** [comment]
@LiFaytheGoblin This doesn't appear to be an issue with your PR as the same error is being thrown in #1770. Judging by the error report (`not ok ./node_modules/scratchr2_translations/www/translations/scratch-website.about-l10njson/cy.json has invalid Json.`) it appears that for some reason the PR's aren't passing the localization json check: https://github.com/LLK/scratch-www/blob/develop/test/localization/check_valid_json.js 

Perhaps something done in the scratchr2 repo could have broken something? @thisandagain @mewtaylor @rschamp

**Comment by Kenny2github** [comment]
@amazinigmech2418 checks don't fail from warnings. They only fail from errors, and as per what St said it's that particular error that is cascading.

**Comment by amazinigmech2418** [comment]
@St19Galla Maybe some quotes were removed... Can I have the link to the file?

**Comment by chrisgarrity** [comment]
@LiFaytheGoblin there was a newline in the Welsh translations that was breaking the build. I've fixed the translation and restarted the build. Hopefully it'll build cleanly this time.

**Comment by Narulacodes** [comment]
@chrisgarrity  Can you see what's wrong in #1770

**Pull request merged**
