### PR TITLE
[hotfix] Change country to location

### PR DESCRIPTION
**Pull request by apple502j**
Hotfix version of #4316

### CODE REVIEW

**Comment by R4356th** [comment]
There would be huge drama in the community if it was merged. Scratchers from Hong Kong, Taiwan etc. would be very sad.

**Comment by Accio1** [comment]
@R4356th You have to think of the pros and cons. If merging this allows Chinese Scratchers to access Scratch, then that probably outweighs the downsides of Scratchers from Taiwan and Hong Kong being sad about the change.

**Comment by R4356th** [comment]
> @R4356th You have to think of the pros and cons. If merging this allows Chinese Scratchers to access Scratch, then that probably outweighs the downsides of Scratchers from Taiwan and Hong Kong being sad about the change.

Only 5.72% of Scratchers live in China; other Scratchers might not be with them.

**Comment by R4356th** [comment]
> @R4356th You have to think of the pros and cons. If merging this allows Chinese Scratchers to access Scratch, then that probably outweighs the downsides of Scratchers from Taiwan and Hong Kong being sad about the change.

And there is no guarantee that this will ensure China would unblock Scratch.

**Comment by ljy-002** [comment]
> There would be a huge drama in the community if it was merged. Scratchers from Hong Kong, Taiwan etc. will be very sad.

yes

**Comment by ljy-002** [comment]
> > @R4356th You have to think of the pros and cons. If merging this allows Chinese Scratchers to access Scratch, then that probably outweighs the downsides of Scratchers from Taiwan and Hong Kong being sad about the change.
> 
> Only 5.72% of Scratchers live in China; other Scratchers might not be with them.

Only？That's not less

**Comment by apple502j** [comment]
I don't think this gets merged nor merging this is enough to get unblocked. China's censorship is much harder than Scratch's...

**Comment by cyx2015s** [comment]
Anyway, I translated “country” into “location”.

**Pull request closed without merging**
