### PR TITLE
Add Tina Quach to Credits

### PR DESCRIPTION
**Pull request by GreenBayRules**

### CODE REVIEW

**Comment by thisandagain** [comment]
Tina should be added to the `<p><FormattedMessage id='credits.developers' /></p>` section rather than the moderators section.

**Comment by GreenBayRules** [comment]
Okay ill fix it :D

**Comment by GreenBayRules** [comment]
I'll make a new pull request.

**Comment by GreenBayRules** [comment]
#1574 Done, that should add her to developers.

**Pull request closed without merging**
