### PR TITLE
Revert "Send fastly token to gui"

### PR DESCRIPTION
**Pull request by picklesrus**
Reverts LLK/scratch-www#6773

This breaks uploading via file upload so reverting til we can figure out a better fix.

### CODE REVIEW

**Comment by KazookiTV** [comment]
Whoooo yeah babyyyyy that’s what the scratch community has been waiting for!

**Comment by CST1229** [comment]
> Whoooo yeah babyyyyy that’s what the scratch community has been waiting for!

It will be unreverted sometime.

**Comment by TimMcCool** [comment]
> Whoooo yeah babyyyyy that’s what the scratch community has been waiting for!

This only delays the implementation of the project token, it doesn't meant that it's canceled.

**Comment by KazookiTV** [comment]
> > Whoooo yeah babyyyyy that’s what the scratch community has been waiting for!
> 
> This only delays the implementation of the project token, it doesn't meant that it's canceled.

It’s still amazing because we still have a couple of weeks of unshared project viewing

**Pull request merged**
