### PR TITLE
Removes the community moderator & adds hyphen to the moderator page.

### LINKED ISSUE #1442: Remove Community Moderator Job listing
https://scratch.mit.edu/jobs/moderator needs to come down as the position has been filled.

---
Moved from LLK/scratchr2#4729
/cc @dietbacon

### PR DESCRIPTION
**Pull request by VutonDesign**
## Resolves
- #1442 (re-opened by @dietbacon)
- #1596

## About
Removes community moderator job listing & adds a hyphen to the moderator job page.

### CODE REVIEW

**Comment by VutonDesign** [comment]
@thisandagain I've added the hyphen fix to this pull. 👍

**Comment by VutonDesign** [comment]
@thisandagain It's been a couple of days now, Could this get a review?

**Comment by VutonDesign** [comment]
No Problem 😄

**Comment by mewtaylor** [comment]
On staging, Chrome 61, OSX 10.12:
* The hyphen appears in the moderator page now
* The moderator job link is removed from the `/jobs` page

Marking this as `QA-OK`

**Pull request merged**
