### PR TITLE
Fix gh-1588: Localize "it's free!" String

### LINKED ISSUE #1588: String ( it's free ) lacks translation markup
I have searched all projects on Transifex for the string "free", but I could not find an entry for "( it's free )".

scratch-free

### PR DESCRIPTION
**Pull request by TheGrits**
Resolves #1588 

## Test cases:
- component string should still read "it's free!" while using English
- component string should now be in Transifex

### CODE REVIEW

**Comment by TheGrits** [comment]
@chrisgarrity

**Comment by chrisgarrity** [comment]
Thanks @TheGrits looks good - I'll do a proper review a bit later when I have time to run it :)

**Comment by chrisgarrity** [comment]
@TheGrits do you have time for this change? If not I'll make the update.

**Comment by TheGrits** [comment]
@chrisgarrity Whoops sorry yeah I can make this change quick

**Comment by TheGrits** [comment]
@chrisgarrity Should be good to go now!

**Comment by chrisgarrity** [comment]
👍  @TheGrits looks good - thanks!

**Comment by TheGrits** [comment]
@chrisgarrity My pleasure!

**Pull request merged**
