### PR TITLE
Fix travis build fail

### PR DESCRIPTION
**Pull request by TheGrits**
Travis was complaining that link 188 had over 120 characters, this should fix it.
Here's where I saw it: https://github.com/LLK/scratch-www/issues/358#issuecomment-181396113

### CODE REVIEW

**Comment by mewtaylor** [comment]
@TheGrits I'm not getting a lint failure on this line locally when I test the `develop` branch – is that the branch you were seeing it on?

Also in the future I think it'd be easier to open an issue before submitting a PR, just to make sure it can be reproduced first.

**Comment by TheGrits** [comment]
@mewtaylor I saw it here: https://github.com/LLK/scratch-www/issues/358#issuecomment-181396113

**Comment by mewtaylor** [comment]
Awesome thanks @TheGrits can repro now – would you mind updating the PR description to include the link to the comment?

**Comment by TheGrits** [comment]
@mewtaylor Done.

**Comment by mewtaylor** [comment]
@TheGrits looks great, just confirmed the fix locally. Thanks!

**Pull request merged**
