### PR TITLE
Fix #1649: Edit Scratch Conf Website - Correct Info for Costa Rica Conf

### LINKED ISSUE #1649: Edit Scratch Conf Website - Correct Info for Costa Rica Conf
Please update the following details for the listing for Scratch Conference Costa Rica (on scratch.mit.edu/conference): 

* Change the date from “November 10, 2017 - November 12, 2017” to “November 12, 2017” 

* Change the text on the orange button to read “Visit Website”

* Link the button to https://scratchcostarica.com/

### PR DESCRIPTION
**Pull request by GreenBayRules**
Changed the button to "Visit Website"
Changed button link to "https://scratchcostarica.com/"
Changed the date to be: "November 12, 2017"

### CODE REVIEW

**Comment by GreenBayRules** [comment]
Sorry that there are many commits, I was trying to figure out how to make two pull requests at the same time, and then I imported the wrong files lol.

**Comment by GreenBayRules** [comment]
Passed :D

**Comment by thisandagain** [comment]
Note: this should be squashed before merging.

**Comment by GreenBayRules** [comment]
@mewtaylor Can you remove the pr needs review tag, since you reviewed it?

**Pull request merged**
