### PR TITLE
changes requested in #1702 ; New Image

### PR DESCRIPTION
**Pull request by redmangospros**
This Adds The Image @me-win  Asked to be in the scratch conf website for 2018. his adds it both in the static images and Scss.

#1702

### CODE REVIEW

**Comment by vutondesign** [comment]
It's recommended that you put all the changes requested in the issue in the one pr, instead of splitting them up.

**Comment by vutondesign** [comment]
Also, What was the filler file for?

**Comment by redmangospros** [comment]
I  was using my chromeos and couldn't add a file, so i had to add a file when creating the 2018 static images. I will Close #1724 and add everythign here

**Comment by thisandagain** [comment]
Tracking full fix in #1727. In the future, please only submit PRs that cover an entire issue unless you ask first. Many thanks!

**Pull request closed without merging**
