### PR TITLE
Migrate FAQ, restyle Privacy Policy and DMCA

### LINKED ISSUE #307: Migrate - FAQ

### PR DESCRIPTION
**Pull request by technoboy10**
This PR fixes #307 as well as restyling the Privacy Policy and DMCA pages to use the same style.

Once #512 is merged, I can add a redesign for Terms of Use into this PR as well.

**Potential additions**
I'd like to move the scss file for all of the static pages into one global file, if possible, since they all use the exact same styling with the exception of which div they are applied to. (using sass's include feature, perhaps?)

### CODE REVIEW

**Comment by TheGrits** [comment]
@technoboy10 Heads up! (To save you from unnecessary work) I was told by @rschamp that the legal pages like the Privacy Policy page shouldn't have translation strings. (I did them, then he told me to remove them. 😛 So I learned the hard way. lol) And since the DMCA page is also a legal page, I would think that it's safe to assume that doesn't need translation strings either.

**Comment by technoboy10** [comment]
@TheGrits Phew, thanks for letting me know! :D That wasn't going to be much fun. :package:

**Comment by TheGrits** [comment]
@technoboy10 Haha, no problem. I just didn't want you to go through the same thing as I did. lol

**Comment by rschamp** [comment]
I assume this is for next iteration?  Looks like something is up with this branch, it's trying to pull in something of mine that's already in there? We can take a look at rebasing this and fixing conflicts next week.

**Comment by technoboy10** [comment]
@rschamp Yeah, this is for next iteration. It's based on release/2.2.9, so I figured that once that branch is merged into develop the conflicts should be resolved (hopefully!).

**Comment by technoboy10** [comment]
Going to redo the PR so it's based on the latest `develop` branch.

**Pull request closed without merging**
