### PR TITLE
Delete all Community Blocks Interview related files

### LINKED ISSUE #4187: Community Blocks Interviews page is still accessible
The Community Blocks Interviews page is still accessible and present in this repository even though that is an old and inactive project.

### Steps to Reproduce

Go to https://scratch.mit.edu/info/communityblocks-interviews.

### Operating System and Browser

N/A

### PR DESCRIPTION
**Pull request by R4356th**
### Resolves:

Resolves #4187.

### Changes:

Deletes all Community Blocks Interview related files.

//cc @benjiwheeler

### CODE REVIEW

**Comment by apple502j** [comment]
You forgot to delete the routing... /src/routes.json

**Comment by R4356th** [comment]
Thank you, @apple502j! 💯

**Comment by benjiwheeler** [comment]
This looks good to me at first glance -- I'll test it soon so we can merge it! It's currently scheduled to be tested in September.

**Comment by Naleksuh** [comment]
These files do not need to be removed

**Comment by R4356th** [comment]
>could you elaborate more on this?
Yes, just as I mentioned in #4187, community blocks was a research project the ST was working on but it is not active anymore and the pages about that are not supposed to be accessible anymore.

**Comment by benjiwheeler** [comment]
I added one change, which was to remove "communityblocks-interviews" from the routeAlias regex entries.

Thanks, @R4356th !

**Pull request merged**
