### PR TITLE
Optimize all the things!

### PR DESCRIPTION
**Pull request by as-com**
This PR just catches some low-hanging fruit for better performance in both development and in the browser.

- [x] Don't use `eval` devtool in production (much better parsing performance and smaller bundles)
- [x] Only use UglifyJS in production (faster dev builds)
- [x] Add support for latest Node.js (#1144) for faster build times and less memory usage (oops already covered by #1671)
- [x] Upgrade Webpack to 3.x for even faster builds and optimization opportunities
- [x] Enable caching in babel-loader for faster builds
- [x] Babel plugin for React optimizations
- [x] Figure out what's bloating these bundles
- [x] Minify CSS
- [x] HTML minification
- [ ] Only require large libraries like libphonenumber when needed (remove from common chunk)
- [ ] Lodash
- [ ] UglifyJS parallelization
- [ ] Image optimization

Stretch goals:
- [ ] Hashed filenames for easier cache invalidation
- [ ] Lazy-load these large validation libraries
- [ ] Use `cache-loader` and `thread-loader` for some assets
- [x] Migrate to ES6 modules
  - [x] Webpack tree shaking
  - [x] Webpack scope hoisting
- [ ] Get rid of `React.createClass`
- [ ] React 16
- [ ] TypeScript? (avoid common errors, also produces cleaner/faster code than Babel)

### CODE REVIEW

**Comment by as-com** [comment]
Progress report:

screenshot-2017-11-24 webpack bundle analyzer

That's a lot of phone numbers.

**Comment by as-com** [comment]
screenshot-2017-11-24 webpack bundle analyzer 1

- Do we really need libphonenumber, iso3166, and react-intl everywhere?
- Can they be lazy-loaded?

**Comment by Kenny2github** [comment]
Looks like you've got a syntax error in `es_419.json`:
image

**Comment by as-com** [comment]
@Kenny2github That looks like a problem in their translation server.

**Comment by mewtaylor** [comment]
@as-com thank you so much for looking into all of these ergonomics issues! These kinds of optimizations are incredibly helpful for everyone who contributes, so your work is really appreciated here.

In order to handle all of these potential optimizations, I have a few requests for how you can submit these changes in a way that will be easiest for us to handle:
* **Make separate github issues for each of the checklist items you have mentioned above**. Please tag them with the [ergonomics](https://github.com/LLK/scratch-www/issues?q=is%3Aopen+is%3Aissue+label%3Aergonomics) label, if they are not already opened in this repo.
  * This will help us determine if each of the individual optimizations are things we would like to see in the repo right now or not.
* **Separate out the optimizations here into separate PRs associated with each type of optimization**.
  * Doing this in separate issues and PRs will make it easier for us to review the changes, and it will also make it easer for us to test these changes. There are a lot of great things here, yet merging them all at once will make it hard for us to figure out what causes what, if issues arise from them in testing. 

**Additionally, for the es6 changes specifically** – we will have a maintainer make these changes in order to make an upgrade that's in line with the style of our other es6 repos, so you can pause on that one! I will make separate issues for the es6 upgrades right now myself so that they're being tracked too.

Thanks again, and please let me know if you have any questions!

**Comment by mewtaylor** [comment]
@as-com as for some of your specific questions:
* `libphonenumber` is probably not necessary everywhere, so finding a way to load it with the bundle it's used in only seems like something that would be useful to research
* `react-intl` and `iso3166` are indeed needed everywhere, since they handle the localization of individual pages

Also, we plan on updating the way we import translated strings once we move to es6, so we will likely look at the redundancy you mentioned in `intl` files then, and see if reducing the redundancy would help at all with page load times/bandwidth.

**Comment by as-com** [comment]
Closing in favor of #1689, #1690, #1691, #1692, and #1671.

**Comment by mewtaylor** [comment]
@as-com awesome, thank you very much!

**Pull request closed without merging**
