### PR TITLE
[DEVELOP] Conference site updates - schedule, logos, room locations 

### PR DESCRIPTION
**Pull request by shickey**
This PR updates the 2018 conference website. In particular:

- The schedule is updated on the "What to Expect" page
- Added Cartoon Network logo
- Reverted LEGO Education logo to LEGO Foundation
- Added room locations to schedule pages

### CODE REVIEW

**Comment by colbygk** [comment]
I think the .travis.yml changes are coming in via a previous hotfix, we definitely do not want those encrypted values in .travis.yml anymore.

**Comment by chrisgarrity** [comment]
Yes, the issue is that this is branching from Master and merging into develop. It would be good to have a PR on develop that just includes @shickey 's commits, not the others.

**Comment by shickey** [comment]
Ah, thanks all. I meant to check in with someone about this before I headed out. Hopefully there won't be many/any further updates needed for the conference site, but if it turns out there needs to be more, I'll ask...@rschamp(?) about the best method for creating future PRs.

**Comment by chrisgarrity** [comment]
@shickey what you did was fine, it just got caught by the fact that we'd had a few other hotfixes in the meantime, and we're frozen for the next monthly deploy.

**Comment by shickey** [comment]
👍 Gotcha. Thanks @chrisgarrity !

**Pull request merged**
