### PR TITLE
Fix gh-555: Squished News Icons

### LINKED ISSUE #555: Squished icons in Scratch News (Safari)
Safari Version 9.1 (11601.5.17.1)

Steps to repro: Log in to Scratch in Safari; Go to Homepage; Check out the icons in the Scratch News section.

Reported by: https://scratch.mit.edu/discuss/topic/200418/?page=1#post-2018413

screen shot 2016-06-06 at 3 00 45 pm

### PR DESCRIPTION
**Pull request by TheGrits**
Should fix #555 
@Choco31415 came up with the fix and tested it in Safari, I have tested it locally on Chrome 51.

### CODE REVIEW

**Comment by TheGrits** [comment]
@thisandagain @mewtaylor @rschamp (@technoboy10?)

**Comment by Choco31415** [comment]
@TheGrits : The PR as is does not work. The flex-shrink has to specifically target the  element.

Here it is on the news box: http://u.cubeupload.com/Choco31415/860ScreenShot20160613at.png (Fail)

Here it is on a news li item: http://u.cubeupload.com/Choco31415/73bScreenShot20160613at.png (Fail)

Here it is on a new image: http://u.cubeupload.com/Choco31415/440ScreenShot20160613at.png (Success)

**Comment by TheGrits** [comment]
@Choco31415 Good call, I forgot that I have to put it on the `img` element, and not on the entire thing. I'll fix it now. Thanks!

**Comment by technoboy10** [comment]
@TheGrits Thanks, this looks great!

Tested on Chrome 51, Safari 9.1.1, and Firefox 46 on OS X 10.11 and found no side effects.

**Testing steps**
- Open the splash page on Safari and log in.
    - News icons should not appear squished
    - Other images on page should appear normally
- Check that the news images look normal on other browsers.

**Pull request merged**
