### PR TITLE
For GH-835: Update max length copy

### PR DESCRIPTION
**Pull request by mewtaylor**
This is an update for #842 to add new copy based on feedback given on PR #841. Thanks @kaschm and @jwzimmer!

### CODE REVIEW

**Comment by mewtaylor** [comment]
fyi @kaschm @jwzimmer

**Comment by jwzimmer** [comment]
In Chrome, the message is overflowing the validation:
screen shot 2016-08-15 at 5 20 02 pm

I don't think we'd want to push to production with that issue, so I switched the labels from pr - good to merge to pr - needs review to make sure that wouldn't happen, let me know if you would prefer me signal that elsewise, @mewtaylor. : )

**Comment by mewtaylor** [comment]
@kaschm thoughts on taking out the word "maximum"? If we want to keep it in I can change the max height of this though

**Comment by jwzimmer** [comment]
Looks really good

Just a few questions, very minor questions:
1) Do we want the validation message to have a different shaped bubble for some of the fields, e.g. the Type of Org > Other validation is different than the Website validation:
screen shot 2016-08-16 at 9 34 07 am
2) Do we want to be consistent with telling people the max char length in the validation as we decided to do with the Use field, or do we want to treat that as a special case (since it is a more open-ended field)?
screen shot 2016-08-16 at 9 35 55 am

screen shot 2016-08-15 at 5 20 02 pm

**Comment by mewtaylor** [comment]
@jwzimmer the issue with different sized bubbles is related to the offset issue being tracked in https://github.com/LLK/scratch-www/issues/775#issuecomment-236697946. As for the different messages – I think it's okay since that's the only open text area, whereas the others are input fields, but also happy to change it.

**Comment by jwzimmer** [comment]
@mewtaylor Ah, okay re different sized bubbles. : )
For the different messages, I think having them be different is fine, since the fields do have different roles, as you said. So looks good to me. 👍

**Pull request merged**
