### PR TITLE
Added support for redirect routes

### LINKED ISSUE #412: Redirect old 'donate' page
This page:
https://scratch.mit.edu/info/donate/

Should redirect (forever) to:
https://secure.donationpay.org/scratchfoundation/

### PR DESCRIPTION
**Pull request by sclements**
Added code for redirects and now redirecting the donation URL to the proper location. Fixes #412.

### CODE REVIEW

**Comment by sclements** [comment]
This simply adds redirect support. I'd like to add Jasmine tests in a subsequent PR if there is no objection to using Jasmine for testing.

**Comment by mewtaylor** [comment]
@rschamp assigned you just in case this has any relation to the stuff you're exploring right now with react-router. If you don't have time though, I can certainly take a look!

@sclements first of all – 
confetti-horn-emoji
you're amazing!

Second of all – we're not 100% about if we're going to be using Jasmine just yet. If you wouldn't mind holding off until a bit later next week on that one, that'd be great. And I (or Ray) can get back to you about that as soon as we know!

**Comment by sclements** [comment]
Thanks @mewtaylor! LMK about Jasmine. I wanted the ability to mock requests and have more testing tools at my disposal.

@rschamp I had considered putting redirects in a separate file but I was concerned about accidental overlapping routes in the future.

**Comment by rschamp** [comment]
@sclements We're planning to remove the server from this repo entirely and decided to handle redirects like this on the CDN (Fastly). Sorry to close your first scratch-www PR :( It was fun to see it come in from you though!

**Comment by rschamp** [comment]
@sclements As part of the work to remove the server, we needed to have the Fastly configuration as part of the deployment. And then that made sense to bring these redirect routes back in. So FYI I merged your PR into the work for that here: https://github.com/LLK/scratch-www/pull/425

**Pull request closed without merging**
