### PR TITLE
update translation URL

### LINKED ISSUE #4273: Out of date link on Around the World section of the About page
The last sentence of Around the World links to the obsolete wiki page:

> To add or improve a translation, see the [translation](https://en.scratch-wiki.info/wiki/How_to_Translate_Scratch) page.

It should link to https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators

Ideally we'd also replace the image - the list of languages is from Scratch 2.0, and they are not all part of Scratch 3. Also, it's very Euro-centric. (Note: moved this point to its own issue: https://github.com/LLK/scratch-www/issues/4403 )

Where it says "and available in more than 40 languages", it should say 60 instead of 40.
### Steps to Reproduce

https://scratch.mit.edu/about

### PR DESCRIPTION
**Pull request by doc-han**
### Resolves:

Resolves #4273

### Changes:
Changes the URL of the translation guide from [https://en.scratch-wiki.info/wiki/How_to_Translate_Scratch](https://en.scratch-wiki.info/wiki/How_to_Translate_Scratch) to [https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators](https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators)

### CODE REVIEW

**Comment by benjiwheeler** [comment]
This looks good to me at first glance -- I'll test it soon so we can merge it! It's currently scheduled to be tested in September.

**Comment by doc-han** [comment]
great!

**Comment by chrisgarrity** [comment]
@doc-han I just updated the issue because we realized that we also need to change the number of languages from 40 to 60. Can you make that change to this PR too? Thanks /cc @benjiwheeler

**Comment by benjiwheeler** [comment]
Ready to merge, just waiting to hear if there is any way to make updating this string easy for translators

**Pull request merged**
