### PR TITLE
CE-292: Confusing tab navigation on explore page for screen readers

### LINKED ISSUE #7198: CE-292 Confusing tab navigation on Explore page for screen readers
### Expected Behavior

The tabs for filtering categories on the [Explore page](https://scratch.mit.edu/explore/projects/all) should have a simple description of the tab name along with a description of the interactive state (for example: "Projects tab selected" or "Studios tab" if not selected).

### Actual Behavior

Tabs are currently read by screen readers in a confusing way. Some tabs also include graphics without alternative text description. For example, a selected tab may be read as "Link Graphic tabs/projects-active", making it difficult for screen reader users to interpret what happens when a tab link is clicked. 

### System Details
Browser: Chrome/Firefox/Safari, Screen Reader: Jaws/NVDA/Voiceover

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Paul-Clue**
### Description:

The `/explore` page and the `/search` page had to be refactored. The way that the tabs were set up would have confused screen reader users because the proper aria attributes were not present, and the implementation of the tabs would not allow the screen reader to announce that section properly to screen reader users. The refactor used aria APG (Authoring Practice Guide) specification and implemented arrow key support. Resolves #7198.

### Test Cases:
No new tests have been added. All current automated tests still pass and nothing breaks in the original design of the application.

### CODE REVIEW

**Comment by Paul-Clue** [comment]
Can @chrisgarrity review this pull request when time permits.

**Comment by ChrisC** [comment]
This will also close #7171

**Comment by corihudson** [comment]
Hi @Paul-Clue! Thanks for this PR. I haven't been able to get VoiceOver on macOS to read out any of the category bubbles on the explore page - is that a part of this PR or a separate issue? (and if that's not covered in this PR, is there a reason for the "selected" strings for those bubbles to be added here?) Thanks!

**Comment by Paul-Clue** [comment]
Hey, @corihudson, I fetched the branch and ran it locally. I am not having trouble with VoiceOver reading the category bubbles on the explore page: 
Screenshot 2023-04-03 at 11 08 14 AM
Screenshot 2023-04-03 at 11 10 21 AM
Screenshot 2023-04-03 at 11 09 59 AM
Screenshot 2023-04-03 at 11 09 42 AM
Screenshot 2023-04-03 at 11 09 26 AM
Screenshot 2023-04-03 at 11 09 08 AM
Screenshot 2023-04-03 at 11 08 47 AM

I will ask a teammate if they experience any trouble with using VoiceOver on that branch and get back to you.

**Comment by alflennik** [comment]
Hi @corihudson! I'm @Paul-Clue's colleague and I was able to test this branch successfully with VoiceOver - I got the same output as the screenshots he was sharing.

**Review by corihudson — APPROVED** [review]
Hi @alflennik, @Paul-Clue! Thanks for clarifying - I'm now getting the same output, not sure what was happening earlier! These changes look good to me. Thanks!

**Pull request merged**
