### PR TITLE
Auto mod/update copy

### LINKED ISSUE #4896: Revise copy of messages for muting
Update the muting messages with the revised content in the doc: https://docs.google.com/document/d/1IRVumeEXeQuCWVJbYMBGvS9MYtEfs73CtgTv81PHiFU/edit?usp=sharing

### PR DESCRIPTION
**Pull request by chrisgarrity**
### Resolves:

fixes #4896 

### Changes:
* replace disrespectful messages with general ones
* update messages for pii, unconstructive, and vulgarity
* reduce the max width of the comment status text to make it easier to read

### Testing:
Check that text matches the current copy in the [messaging doc](https://docs.google.com/document/d/1IRVumeEXeQuCWVJbYMBGvS9MYtEfs73CtgTv81PHiFU/edit?usp=sharing)

### CODE REVIEW

**Comment by SausageMcSauce** [comment]
For comment.general.content1, 'friendly' is misspelt. Maybe that could be fixed?

**Comment by seotts** [comment]
Aside from the spelling issue that @SausageMcSauce caught, this looks good to me!

**Comment by chrisgarrity** [comment]
thanks for catching the typo @SausageMcSauce

**Review by seotts — APPROVED** [review]
lgtm!

**Pull request merged**
