### PR TITLE
remove email opt-in from join flow

### PR DESCRIPTION
**Pull request by benjiwheeler**
Resolves https://github.com/LLK/scratchr2/issues/5723

### Changes:

* removes email opt-in checkbox from join flow
* omits `subscribe` parameter, which will default to False in scratchr2
* removes email opt in string
* removes tests that no longer apply

### Test Coverage:

_Please show how you have added tests to cover your changes or describe how you have tested the changes (include a screenshot if possible)._

### CODE REVIEW

**Comment by Accio1** [comment]
I'm just curious, why are you removing this option? I can't see the issue that it fixes because it's in a private repository.

**Comment by benjiwheeler** [comment]
@Accio1 I wasn't part of the decision, but the reasoning was basically that we don't use the mailing list much and don't plan to, and further it would take engineering work to store opt-in info in other ways besides the mailing list itself.

**Comment by benjiwheeler** [comment]
Marked this good to merge per conversation with @picklesrus on Slack

**Comment by benjiwheeler** [comment]
Closing per doing this as hotfix instead in https://github.com/LLK/scratch-www/pull/4096 and https://github.com/LLK/scratch-www/pull/4097

**Pull request closed without merging**
