### PR TITLE
Merge develop into auto-mod branch

### PR DESCRIPTION
**Pull request by chrisgarrity**
Bring the latest auto-mod changes from develop into the hotfix branch.

### CODE REVIEW

**Comment by apple502j** [comment]
Can you delay the hotfix until the next week so that the updated message is localized? @chrisgarrity

**Comment by picklesrus** [comment]
@apple502j this hotfix won't actually turn on/allow users to see the new message yet. That'll happen separately and won't be today.

**Comment by apple502j** [comment]
Then what's the point of hotfixing?

**Comment by picklesrus** [comment]
Testing and debugging is one reason, yes. There are also other moving pieces to manage.

**Pull request merged**
