### PR TITLE
Implement GH-982: Add hoc event row

### PR DESCRIPTION
**Pull request by mewtaylor**
still missing the video and studio link for content, otherwise should be good to go. Implements #982.

### Test Cases ###
* HOC Event Row should appear when logged in
* HOC Event Row should not appear when logged out
* HOC Event Row should be below the "Featured Studios" carousel
* "See the studio" button should link user to [this studio]()
* Video should play in place on Desktop
* Video should do whatever your mobile device does to play it on mobile ¯\_(ツ)_/¯ 
* Clicking "Dismiss" Should hide the HOC event row immediately and forever after
  * the weight of eternity should fall heavy on your shoulders after dismissing
* The row should follow the responsive behavior as outlined by the illustrious @carljbowman in #982

### CODE REVIEW

**Comment by mewtaylor** [comment]
@rschamp if you could review this anyways, I think the hope is to get it on staging without the video and studio as soon as we can to start testing, since we won't have finalized video content for another day or so.

**Comment by jwzimmer** [comment]
### Testing

- Continued from https://github.com/LLK/scratch-www/issues/982#issuecomment-263716387
- [ ] Tablet
- **Android Asus tablet, Chrome 54.0.2840.85**
  - Name: Quiche
  - Landscape orientation, looks like Desktop state
    - When signed out, no HOC event row
    - When signed in, HOC event row is present
  - Portrait orientation, tablet state
    - When signed out, no HOC event row
    - When signed in, HOC event row is present
- **Apple iPad tablet, Safari**
  - When signed out, no HOC event row
  - When signed in, HOC event row is present
  - Landscape orientation looks like desktop state
  - Portrait orientation looks like tablet state
  - Using Farsi, no obvious issues
    - Can dismiss HOC event row
    - If I sign in & out, the HOC event row appears & disappears
      - Clicking sign in/ out registers with tile underneath; causes hover effects --> 
    - If I sign in, dismiss the row, then sign out, then sign in again, it does not reappear

**Comment by jwzimmer** [comment]
@kaschm I just want to verify two things:
1) in the outro of the CN video, they plug their channel/ other videos, I assume that's fine but I just want to check
2) the next video recommended by youtube comes up. Whatever that next video is, it's then displayed in the HOC event row on the homepage. On refresh, the video resets to displaying the CN How to Create New Characters video. I was just considering a scenario where this is at a public/ shared computer, and the video youtube recommends might not be appropriate for the Scratcher... I don't know if there's anything we can do about that, but figured I'd bring it up?

screen shot 2016-11-29 at 7 34 11 pm
screen shot 2016-11-29 at 7 31 51 pm

**Comment by jwzimmer** [comment]
@carljbowman, I noticed that on my iPhone 6s the HOC event row looks more "squished" than it does in your design spec. I think this is just due to my phone being fairly small, but I wanted to verify that with you.
img_2579

**Comment by coke11** [comment]
@jwzimmer  Are you guys changing the menu bar color?

**Comment by mewtaylor** [comment]
@coke11 nice catch :). No, we're not changing it, that's just the nav color we have on our own staging site for testing purposes.

@jwzimmer @kaschm I didn't realize there was a setting to turn off post-video related video stuff, so I'm going to add that in now.

As for the squishiness – I think that's due to the font size being larger here, and the padding on the top needing to be slightly larger than the other sides. I'll adjust it accordingly.

**Comment by kaschm** [comment]
@carljbowman do we want to create a static thumbnail for the video (that when clicked, opens and plays the vid)? Can we do this? Agreed we should try our best to control the visual experience, esp on the homepage.

**Comment by mewtaylor** [comment]
@kaschm see #1091 – we shouldn't need that in order to prevent seeing related videos, if that's what the static thumbnail issue is trying to address

**Comment by mewtaylor** [comment]
@kaschm @jwzimmer if desired, we could also remove the playback controls, so that it's just the video itself (pausing could still be achieved through clicking on the video, but muting, going to youtube, etc could not be done)

**Comment by kaschm** [comment]
:+1: looks good.

**Comment by mewtaylor** [comment]
Thanks @kaschm ! @jwzimmer the padding and the related videos issues should be fixed now, thanks :).

**Comment by jwzimmer** [comment]
_Compatibility_
**Edge 38.14393.0.0 on Windows 10**
- [x] HOC event row appears below Featured Studios
- [x] Appears when logged in
- [x] Dismiss button has an X
  - [x] Dismissing event row works
  - [x] Refreshing page doesn't bring back event row
- [x] Video thumbnail looks correct
  - [x] Video plays in place
  - [x] Post @mewtaylor's fixes to video playing related videos, outro now just shows CN screen (no videos) and no suggested next video appears, you can still click youtube to go to youtube (@kaschm already ok'd the video playing fixes, so all of this must be the expected behaviour).
- [x] Has title
  - [x] Title font is very bold, checked with @carljbowman that this is acceptable
- [x] Has see the studio button
  - [x] Studio 404's on staging & production, I checked with @mewtaylor and this is expected b/c the studio is currently deleted while in progress

**Comment by jwzimmer** [comment]
Appearance on iPhone 6s post padding-fixes by @mewtaylor:
img_2581

**Comment by coke11** [comment]
@mewtaylor Ah, ok just wondering...

**Comment by jwzimmer** [comment]
@mewtaylor confirmed plan for studio with @SpeakkVisually (currently it is still deleted, so 404's).

**Pull request merged**
