### PR TITLE
Center Download Page header

### LINKED ISSUE #1381: Offline editor download page: top paragraph not centered
When the download page is displayed in a wide window, the paragraph at the top of the page ("You can install the Scratch 2.0 editor....") is aligned left and wrapped to an unnecessarily narrow column width.

Note that this problem existed on the old page, but IMO stands out more on the new version of the page.

Screenshot:
image

### PR DESCRIPTION
**Pull request by GreenBayRules**
Fixes #1381 
image

### CODE REVIEW

**Comment by GreenBayRules** [comment]
Hmmm, why did the travis build fail?

**Comment by GreenBayRules** [comment]
It says this: 
image

**Comment by GreenBayRules** [comment]
That should fix it

**Comment by thisandagain** [comment]
See comments in #1381. I don't think this is quite ready for contribution yet. We need to make a decision regarding when to center and when to keep the left alignment.

**Pull request closed without merging**
