### PR TITLE
Fix gh-942: update compatibility & support FAQ response

### PR DESCRIPTION
**Pull request by jwzimmer**
@mewtaylor Would you mind going over this with me when you have time? I wasn't sure what the comment about updating the `bowser` settings meant exactly, and I am also not sure my repository is actually in the state I want it to be (and I don't want to accidentally break anything!). Thank you. : )

Fixes https://github.com/LLK/scratch-www/issues/942.

### CODE REVIEW

**Comment by mewtaylor** [comment]
@jwzimmer this looks good to me! The bowser thing is in scratchr2, so nothing needs to be done here – I can explain what I meant by that another time.

**Comment by mewtaylor** [comment]
@jwzimmer @rschamp if we want this to go into the hotfix, we'll need to re-open this against the right branch. Is that the preference?

**Comment by rschamp** [comment]
I have no preference.  If we do decide to put it into the hotfix, I will suggest just updating the base branch on this PR, you can do that on GitHub now by clicking Edit next to the PR title!

**Comment by kaschm** [comment]
The link to 'Adobe Flash Player' currently goes to the Scratch homepage. I believe it should be something like **https://get.adobe.com/flashplayer/** instead? @mewtaylor

**Comment by kaschm** [comment]
Capturing my issue here: 
https://github.com/LLK/scratch-www/issues/1130

Because it's happening on production, not just staging.

**Pull request merged**
