### PR TITLE
[Master] Hotfix: Allow urls with `ajax` to pass through

### PR DESCRIPTION
**Pull request by mewtaylor**
Needed for https://github.com/LLK/scratchr2/pull/3804

### CODE REVIEW

**Comment by thisandagain** [comment]
Ok. Once everything looks good in staging.

**Comment by thisandagain** [comment]
@mewtaylor Looks like CI failed.

**Comment by mewtaylor** [comment]
@thisandagain doesn't appear to be an issue with the PR, but with git remote config... looking.

**Comment by mewtaylor** [comment]
@thisandagain going to close and re-open to see if that helps....

**Pull request closed without merging**
