### PR TITLE
Fixes #1700 | Update about page 

### LINKED ISSUE #1700: Update Scratch About Page - Credits
Page: https://scratch.mit.edu/about/
Section: "Support and Funding"

Request:
Update list to include Siegel Family Endowment

Current copy:
The Scratch project has received financial support from the National Science Foundation, Scratch Foundation, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, and MacArthur Foundation.

New copy:
The Scratch project has received financial support from the National Science Foundation, Scratch Foundation, Siegel Family Endowment, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, and MacArthur Foundation.

### PR DESCRIPTION
**Pull request by vutondesign**
#### Info
Updates the "Support and Funding" section of the about page.

#### Fixes
#1700

### CODE REVIEW

**Comment by VutonDesign** [comment]
@chrisgarrity I'm not too sure what's wrong now, I've fixed all the other issues...

```not ok about.quotes has duplicates```

**Comment by Kenny2github** [comment]
I don't know either! There isn't a duplicate quote, afaics, and the stack trace doesn't show which line of the file it's checking, only the line of the test script.

**Comment by vutondesign** [comment]
Yeah, I'll wait and see if @chrisgarrity knows why this is happening.

**Comment by chrisgarrity** [comment]
@vutondesign there were a few typos so I just went ahead and made the changes along with formatting updates. Do you have an environment set up where you can run the website? I realized that the `&#39;` in the l10n file needed to be switched to plain old single quotes in FormattedMessage. but that wasn't obvious until I saw the page rendered. Thanks for the help.

**Comment by chrisgarrity** [comment]
BTW, there were two id's that had the value `"quotes"`, but the first one was the header so it really should have been `"Quotes"`. Everything was fine after that :)

**Comment by vutondesign** [comment]
Sorry, I currently don't have an environment set up as my current computer (being replaced in a couple of weeks) doesn't have enough power to run one properly.

**Comment by chrisgarrity** [comment]
@vutondesign this was a challenging change to take on without being able to run the code as there were things that are easy to see on the page that don't stand out in the code (like the `&#39;` getting escaped).

**Comment by vutondesign** [comment]
@chrisgarrity Yeah, it was a lot more challenging than I first anticipated.

**Comment by vutondesign** [comment]
Sorry this process has taken so long, I'm quite new to React.

**Comment by vutondesign** [comment]
Great! 👍

**Pull request merged**
