### PR TITLE
Fix gh-1465: Add Ellen Daoust to Credits

### LINKED ISSUE #1465: Add Mod To Credits Page
We would like to add the following to the [Credits](https://scratch.mit.edu/info/credits/) page under the section that reads "The team of Scratch moderators manages, supports, and improves the Scratch online community":

Ellen Daoust - username [sunnyday4abluejay](https://scratch.mit.edu/users/sunnyday4abluejay/)

### PR DESCRIPTION
**Pull request by St19Galla**
This fixes #1465 by adding Ellen Daoust to the Moderator section of the Credits page.

### CODE REVIEW

**Comment by Kenny2github** [comment]
@chrisgarrity changes approved, merge yet? /cc @christanbalch

**Comment by thisandagain** [comment]
@Kenny2github Please do not bump PRs or issues that you are not assigned to. Please look at the milestone date before leaving comments like this.

**Comment by mewtaylor** [comment]
On Chrome, OSX 10.12:
* Ellen Daoust appears in the moderators section
* The avatar matches correctly

**Pull request merged**
