### PR TITLE
Rewording | 10n.json

### PR DESCRIPTION
**Pull request by VutonDesign**
Rewording so that users know where the link actually takes them. (10n.json )

This is the fixed version of the original pull request.

### CODE REVIEW

**Comment by Kenny2github** [comment]
LGTM

**Comment by chrisgarrity** [comment]
@VutonDesign Thanks for this pr, it does make the link clearer. However, I just want to point out that we don't make wording changes on the site lightly. With Scratch being translated into more than 70 languages any wording change invalidates previous translations, causing more work for translators who are volunteering their time. In general, we're not going to accept wording changes unless there's a definite problem with the current text. Looking for issues tagged '[help-wanted](https://github.com/LLK/scratch-www/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted)', and fixing those is probably more helpful to the team than looking for wording to improve on the site.

**Comment by VutonDesign** [comment]
@chrisgarrity Ah, Thanks.

I'll have a better look next time. 👀

**Comment by Kenny2github** [comment]
@chrisgarrity today's September 20th, matching the milestone date - any update on this?

**Comment by chrisgarrity** [comment]
@VutonDesign congrats on your first scratch-www PR!
confetti-horn-emoji

**Comment by towerofnix** [comment]
By the way, should this text say "through GitHub", not "through Github"? (Note the capitalization.)

**Comment by VutonDesign** [comment]
@towerofnix Good catch! It's actually spelt Github so that needs to be changed. Do you want to fix it or will I?

**Comment by towerofnix** [comment]
You go ahead; you made the original PR, so you might as well make the follow-up one :P

**Comment by VutonDesign** [comment]
@towerofnix Okay 👍

**Pull request merged**
