### PR TITLE
Responsive about page!

### LINKED ISSUE #891: Mobile About Page Video Bug
The video on the About page does not seem to be responsive on my iPhone 5s Safari creating a bad background issue:

Something to consider is whether it would be better to have the video shrink size to fit or move to beneath/above the intro text when the screen size is small.

Also, ignore the white box as messages, that's a known bug on my phone :) Sorry!

### PR DESCRIPTION
**Pull request by sehgalvibhor**
### Resolves:

Closes #891

### Changes:

About page does not seem to be responsive, keeps flowing out of the div. Changing the layout to grid ensures that the page is responsive, video auto flows to the next row in case of reduction in screen size.

### Test Coverage:

Tested on Chrome:

Full Page:
image

Responsive Page:
image

Iphone 5:
image

Tested on Firefox:

Full page:
image

Responsive:
image

### CODE REVIEW

**Comment by benjiwheeler** [comment]
This is helpful! And/but, I believe (@LiFaytheGoblin, can you confirm?) we have chosen not to use CSS grid for now, because compatibility is not quite widely enough established.

https://caniuse.com/#feat=css-grid shows very good adoption so far, but I think we are looking for higher adoption before we move to using grid.

**Comment by benjiwheeler** [comment]
Thanks, that does look like an improvement on the current version! Maybe you can update the code here to use that approach, and I can take a look.

Also -- just a suggestion -- you might want to look at some of the recent changes to preview.scss by @LiFaytheGoblin , and see if there are patterns she used that you might want to use here.

**Comment by sehgalvibhor** [comment]
Sure, I'll check the changes and see if I can replicate them in the about page too.
Thanks!

**Comment by LiFaytheGoblin** [comment]
The flex component MediaQuery could be used to display the video on different places depending on the screen size @sehgalvibhor

**Comment by benjiwheeler** [comment]
@sehgalvibhor If you're not able to take a look at replicating the media query pattern right now, maybe we should just merge in your current changes, since they're an improvement? Then we can always come back and do a more thorough change later.

**Comment by sehgalvibhor** [comment]
@benjiwheeler : Yeah I think I might just need a bit more time to play around with it and test it properly. We can merge the changes however I think Travis is failing. Will have to re-order the CSS properties right?

**Comment by joker314** [comment]
It looks like it!

```
  33:17  error  Expected `display`, found `border`  property-sort-order
  34:17  error  Expected `border`, found `width`    property-sort-order
  35:17  error  Expected `width`, found `height`    property-sort-order
  36:17  error  Expected `height`, found `display`  property-sort-order
```
 So `display` then `border` then `width` then `height`.

**Comment by sehgalvibhor** [comment]
@joker314 : Thanks for reviewing. Fixed it!
@benjiwheeler : We can merge for now.

**Comment by benjiwheeler** [comment]
Thanks, @sehgalvibhor (and @joker314)!

**Pull request merged**
