### PR TITLE
GH-1361: Implement Notifications Page

### PR DESCRIPTION
**Pull request by mewtaylor**
This implements #1361. Still a WIP as we need some design updates in some areas, but the code is likely ready to start being reviewed.

### CODE REVIEW

**Comment by mewtaylor** [comment]
@rschamp @carljbowman fyi merging for now without icons for testing purposes, will add the icons in a separate PR.

**Comment by jwzimmer** [comment]
### Difference in how number of messages is indicated (counter) in old & new Messages page

In the old page, when you are on the messages page, the counter resets to none even if you have undismissed alerts. If you navigate away from the page with undismissed alerts, the counter will then reset to the number of undismissed alerts.

In the new page, the counter continues to display the number of undismissed alerts.

Both behaviours seem okay to me - which is the intended behaviour? @mewtaylor & @carljbowman

**Comment by jwzimmer** [comment]
## Testing

### Questions
- [ ] https://github.com/LLK/scratch-www/pull/1487#issuecomment-326632667
- [ ] Consolidation of identical messages, e.g. "Activity in studio X on day Y"?

### Issues
- [ ] https://github.com/LLK/scratch-www/issues/1497
- [x] https://github.com/LLK/scratch-www/issues/1494
- [ ] https://github.com/LLK/scratch-www/issues/1495

**Comment by jwzimmer** [comment]
### Testing new messages page on multiple devices/ OS/ browsers

Just making sure the new messages page looks reasonable in different environments.

- [x] iPhone 6, Chrome (@jwzimmer's phone)
- [x] iPhone 6, Safari (@carljbowman's phone)
- [x] IE 11, Win 7 VM
- [x] Chrome 60, Win 7 VM
- [x] Chrome 60, Mac OS El Capitan
- [x] Safari 10.1, Mac OS El Capitan
- [x] Firefox 55.0.3, Mac OS El Capitan
- [ ] Android tablet
- [ ] Small apple tablet
- [ ] Large apple tablet

**Comment by jwzimmer** [comment]
Missing icon for forum thread reply - @mewtaylor is fixing! : )
screen shot 2017-09-08 at 4 06 35 pm

**Comment by jwzimmer** [comment]
Additional fixes to issues described in: https://github.com/LLK/scratch-www/issues/1497#issuecomment-328210348

**Pull request merged**
