### PR TITLE
Updating Fashion Game Card To Fix The Size Of It.

### PR DESCRIPTION
**Pull request by VutonDesign**
**Updating Fashion Game Card To Fix The Size Of It.** 
Note - It's on the develop branch.

### CODE REVIEW

**Comment by thisandagain** [comment]
Resolves https://github.com/LLK/scratch-www/issues/1530

**Comment by mewtaylor** [comment]
Thanks so much @VutonDesign :). @ntlrsk does this copy change look alright to you?

**Comment by chrisgarrity** [comment]
Closing this PR as we're not going to merge at this time.

**Comment by VutonDesign** [comment]
@chrisgarrity Ah, I never thought of that. :man_facepalming: 
Thanks Anyway!

**Pull request closed without merging**
