### PR TITLE
Fix gh-427: Footer Wiki Link not working

### LINKED ISSUE #427: Footer Link to Wiki not working
The current link `https://wiki.scratch.mit.edu/` does not work, and if an attempt is made to load the Wiki with that URL it loads forever. 
When I edited the link to `http://wiki.scratch.mit.edu/` with Inspect Element, the Wiki loaded almost instantly.

It appears that the Wiki doesn't even use `https` anyway.

Initial bug report here: http://wiki.scratch.mit.edu/wiki/Scratch_Wiki_talk:Community_Portal#Scratch_to_Scratch_Wiki_Link

### PR DESCRIPTION
**Pull request by TheGrits**
Fixes #427 

Tested locally on Chrome.

Summary of change: 
`https://wiki.scratch.mit.edu/` -> `http://wiki.scratch.mit.edu/`

### CODE REVIEW

**Comment by TheGrits** [comment]
@mewtaylor @thisandagain @rschamp

**Comment by mewtaylor** [comment]
@TheGrits this looks good! if you wouldn't mind rebasing on the current develop branch to address the conflicts that'd be great!

**Comment by TheGrits** [comment]
@mewtaylor Sure! I'm not sure if it can be done with only the web interface, but we'll see...

**Comment by TheGrits** [comment]
@mewtaylor There are still conflicts even after the rebase. Suggestions?

**Comment by rschamp** [comment]
@TheGrits It looks like something went a little weird with your rebase because GitHub is showing 95 files as changed. An easier way to rebase without using git would be to make a new branch from develop and make the commit on that, and then open a new PR for it.

**Comment by TheGrits** [comment]
@rschamp Ah, ok. I'll do that now.

**Comment by TheGrits** [comment]
@mewtaylor Made a new PR to fix the conflicts: #432

**Pull request closed without merging**
