### PR TITLE
Conference 2017: add new landing page, and archive old site

### PR DESCRIPTION
**Pull request by mewtaylor**
This implements both #1086 and #1136, archiving all of the old conference site to `/conference/2016` and making `/conference` point to the new landing page.

One change from the original design is included in the new landing page – the `website/contact` row was removed, and the button language was changed to say `Visit Website` or `Contact Organizer`, depending on what is possible currently for that conference. 

/cc @kaschm @sleggss

### CODE REVIEW

**Comment by jwzimmer** [comment]
### Testing

**Staging, Firefox 51.0.1, Win 7 VM**
* [ ] The 2016 Scratch Conference site should be visible at scratch.mit.edu/conference/2016
  * [ ] https
  * [ ] ending slash should work `/2016/`
  * [ ] Is the 2015 site available similarly?
* [ ] The 2017 Scratch Conference site should be visible at `/conference`
  * [ ] `/conference/`
  * [ ] `/conference/what` should 404?
  * [ ] https

IE 11.0.9600.18537

**Comment by kaschm** [comment]
@jwzimmer some issues I can see off the bat:

- Scratch Bordeaux link is incorrect: currently goes to http://www.scratch201bdx.org/, should go to http://www.scratch2017bdx.org/ (missing the 7) 
- Scratch al Sur description has a typo: currently says "Español (Spanish - simultaneous translation during plenary sessions", needs end-parens, "Español (Spanish) - simultaneous translation during plenary sessions"
- Scratch Costa Rica link broken: http://scratchcostarica.com/
- "Sponsors" footer - are they sponsoring the 2017 conferences? Should we remove this section @sleggss ?

**Comment by mewtaylor** [comment]
Thanks @kaschm ! Fixes for these (so far) are in https://github.com/LLK/scratch-www/pull/1192, I'll wait on merging til I hear about the sponsors footer question too.

**Comment by sleggss** [comment]
@mewtaylor Let's take out the sponsors footer; the Scratch Family footer should stay.

**Comment by jwzimmer** [comment]
Thank you @kaschm 👍

**Comment by mewtaylor** [comment]
@sleggss @kaschm @jwzimmer updated the footer in #1192, can merge in unless we're waiting on a new link for Costa Rica's conference

**Comment by sleggss** [comment]
@mewtaylor I emailed Costa Rica... let's wait a bit more for their response. Thank you!

**Comment by mewtaylor** [comment]
@jwzimmer some responses to the questions:
1. IMHO it should go to the homepage for the given year. The 2016 site is archived, meaning not linked to anywhere, and just kept for posterity. Considering it was created as an isolated site in a sense, I think keeping it as is, pointing to the 2016 homepage, is best.

2. The current nav bar is inheriting the styling that we created for conference nav bars from the old site. I think it'd be good to keep the styling in line with the previous conference site, but am happy to change to the wider out one if others prefer! ( @sleggss @lifeinchords @kaschm )

3. This was an intentional change after a pass with @lifeinchords 

4. It turned out that the grid size is smaller in actuality than on the mock, so @lifeinchords and I opted to keep the flag bigger – and therefore conforming to the grid – rather than the mock size, and consequently breaking out from the established grid

5. I defer to others on the capitalization – apologies on that if it was meant to be capitalized!

6. After further convo this appears to be a vm-specific issue

7. This seems to be a difference in the svg versus our built-in white shade for the site. I think it best to leave this as is, rather than changing the flag's svg (seems like it could get political)

8. I can change to add 2017 – I was going off of the copy on the google doc, which does not have the 2017 on it (thoughts @sleggss ?)

9. In the doc, titles have a colon between the main title and the subtitle. For this one, there is a colon between "Conference" and "China*Love" which is why I opted to have it be a subtitle. Thoughts @sleggss ?

10. Yes, sorry I did this intentionally and didn't communicate it well – it seemed important to me to express the language in its actual language where applicable for localization considerations, in the event that translations for this page don't get completed for all languages before the conferences occur.

11. Removed, thanks for seeing this!

12. N/A from ^^

**Comment by lifeinchords** [comment]
Hi Julia, Thanks so much for the thorough check. 

I'm good with leaving things as is on 2., the nav bar spacing, for consistency and 5. too, as I don't think we're using the all-caps pattern anywhere else.

~s

**Comment by lifeinchords** [comment]
If there is a change going out I'd maybe consider for 3., making the Learn more text size the same as the subhead text above it, as you mentioned.

And for 13., I agree, it's a bit weird. Unfortunately I think either way, whether it goes to Scratch home at `/` or to Scratch Conf home at `/conference` it's going to be a bit confusing.  Curious if anyone has thoughts on potential ideas. 

/cc @carljbowman

**Comment by sleggss** [comment]
Thanks for your thorough questions, @mewtaylor @jwzimmer! Answering the questions I'm tagged on:

2. I think we should keep the same styling of the nav bar (as it is in its current state).

8. Adding the year is fine! I'm waiting on updated date info from them; this will get replaced with a concrete date once they have one.

9. The title for their event is "Scratch Conference: China*Love" Which I think should be on the same line (no subtitle). Sorry for the confusion on this!

**Comment by mewtaylor** [comment]
@sleggss ah gotcha thanks for clarifying! re subtitle – should I change that for the other titles that have colons in them too (to all be on the same line)?

**Comment by sleggss** [comment]
@mewtaylor Nope, just China, I think! The rest are actually subtitles.

**Comment by kaschm** [comment]
My responses as well, and I've tried to summarize those responses before me too: 

1) Since this is just a single page and it's odd to link to the page itself, I think we should just make the logo and 'Conference' element unclickable. Either that or leave as-is (redirects to the same page). I think I'm agreeing with @mewtaylor here. 

2) [keep as-is per @mewtaylor and @sleggss]

3) I agree with @lifeinchords to make the "Learn more text size the same as the subhead text above it, as you mentioned."

4) [keep as-is per @mewtaylor ] 

5) [keep as-is per @lifeinchords]

6) [vm-specific issue per @mewtaylor ]

7) I agree it's odd that the white of the flag blends into the background. I'm also assuming a shadow or something would not be ok. Looking at @lifeinchords here. 

8) +1 on adding the date, per @sleggss 

9) +1 on pulling the full China title "Scratch Conference: China*Love" onto one line per @sleggss 

10) +1 on expressing language in original language. I like the change, @mewtaylor !

11), 12) N/A

13) See 1) ... I'm not sure why the logo / text are clickable at all, since we are redirecting to the same page. If they do remain clickable, I think they should go to this page (which is also odd). Thoughts, @carljbowman @lifeinchords ?

14) I think we should update the nav to be 'Conferences' to match the title. @lifeinchords , @sleggss thoughts?

**Comment by sleggss** [comment]
@mewtaylor @jwzimmer @kaschm 

Hi all, I just noticed that the listings are out of order. My apologies! They should be alphabetical by city, according to [this doc](https://docs.google.com/document/d/1WtA2sij_n3gbKCL1MgYQ1CqQVDfnN5u_hrbpAGi2M8c/edit).

**Comment by sleggss** [comment]
@kaschm, I'm ok with updating the nav to say "Conferences". Thanks!

**Comment by mewtaylor** [comment]
The flag issue is actually an issue for all but Brasil and China, it appears. We could put a small border around the flags maybe? thoughts @lifeinchords ?

**Comment by jwzimmer** [comment]
@kaschm if we do change the navbar to say "Conferences", to match the title, then does the URL being "Conference" seem weird? (Personally, I think so, but at this point I doubt we want to change the URL... so then should the title and navbar just be "Conference"...?)

**Comment by kaschm** [comment]
Good point. However, I think it's important to keep the URL consistent from year to year, because folks bookmark it / link to it over time. Personally, I'm okay with the 'Conferences' plural name and 'Conference' singular URL for this year. 

Thoughts @sleggss ?

**Comment by sleggss** [comment]
@kaschm @mewtaylor I think we should keep it consistent ( /conference URL)

**Comment by sleggss** [comment]
@mewtaylor Costa Rica's email address: admissions@treeoflifelearning.com

They'll ping us when the site they've listed is ready.

**Comment by lifeinchords** [comment]
7. ya shadow might be weird in this design. @mewtaylor, checked in with @carljbowman 
The border looks great, let's go with it.

**Comment by jwzimmer** [comment]
@mewtaylor is adding the language dropdown to the footer; at the moment I couldn't see a way to change the language on the conferences page. 👍

**Comment by jwzimmer** [comment]
These icons are super tiny in IE 11/ Win 7 VM:
screen shot 2017-02-22 at 11 43 07 am

**Comment by jwzimmer** [comment]
The links in the conference page footer point to Production rather than staging. I think that might mean the URLs are hard-coded there when they shouldn't be? /cc @mewtaylor

**Comment by mewtaylor** [comment]
@jwzimmer hard coded links are intentional

**Comment by jwzimmer** [comment]
@mewtaylor the scratch link links to scratch.mit.edu, not staging - if that's intentional, then great. : )

**Comment by jwzimmer** [comment]
### Testing

**Basics**

* [ ] The 2016 Scratch Conference site should be visible at scratch.mit.edu/conference/2016
  * [ ] https
    * If you edit the URL to http it redirects to https
    * If you just go to `staging/conference/2016` it loads on https
  * [ ] ending slash should work `/2016/`
    * Does not redirect URL to `/2016`
  * [ ] no ending slash should also work
    * Does not redirect URL to `/2016/`
  * [ ] the 2015 site should be available similarly
* [ ] The 2017 Scratch Conference site should be visible at `/conference`
  * [ ] `/conference/`
    * Does not redirect to `/conference`
  * [ ] `/conference` does not redirect to `/conference/`
  * [ ] https
    * If you edit the URL to http it redirects to https
    * If you just go to `staging/conference/2016` it loads on https
* [ ] Browser tab should say "Scratch Conferences"

**Design**

* [ ] The Conference page should match @lifeinchords' design in https://github.com/LLK/scratch-www/issues/1086#issuecomment-278390219, although title should be "Scratch Conferences" rather than "Scratch Conference" and website for conference should be a button rather than a link
  * [x] Title is Scratch Conferences
  * [x] Links for individual conferences, e.g. Scratch2017BDX, are buttons that say "Visit Website" or "Contact Organizer"
    * [ ] The buttons should work
      * [x] Visit website should take you to the relevant websites
      * [x] Contact organizer should open a mail client

**Post-fixes**

* [ ] The copy & link changes brought up by @kaschm should be fixed

**Details - Copy & design**

* [ ] Check all copy
* [ ] Check all links & buttons
* [ ] Check responsive design
  * [ ] Mobile
  * [ ] Tablet

IE 11.0.9600.18537
* [ ] The 2016 Scratch Conference site should be visible at scratch.mit.edu/conference/2016
  * [ ] https
  * [ ] ending slash should work `/2016/`
  * [ ] Is the 2015 site available similarly?
* [ ] The 2017 Scratch Conference site should be visible at `/conference`
  * [ ] `/conference/`
  * [ ] `/conference/what` should 404?
  * [ ] https

**Comment by jwzimmer** [comment]
After discussing with @lifeinchords, @mewtaylor and everyone in bug triage, none of the outstanding issues are blockers.

#1213 has been resolved (that one was a blocker). https://github.com/LLK/scratch-www/issues/1208 was also resolved (the most serious cosmetic issue).

https://github.com/LLK/scratch-www/issues/1214 has a patch out.

So, I am QA-OK'ing this. 👍

**Pull request merged**
