### PR TITLE
Changes requested in #1702

### PR DESCRIPTION
**Pull request by redmangospros**
Adding a semicolon as requested in #1702 to add a semicolon.
This pull requet adds the following changes

### CODE REVIEW

**Comment by GreenBayRules** [comment]
Again, as I said before I don't  think you should submit a pull request if you are only finishing part of the issue, you should probably solve the rest of the issue then pull request.

**Comment by redmangospros** [comment]
I will, i will do this.
where is the source code for img.

**Comment by redmangospros** [comment]
#1725

**Comment by thisandagain** [comment]
Tracking full fix in #1727. In the future, please only submit PRs that cover an entire issue unless you ask first. Many thanks!

**Pull request closed without merging**
