### PR TITLE
[Master] Show link to view all remixes on project page

### PR DESCRIPTION
**Pull request by benjiwheeler**
### Resolves:

Resolves https://github.com/LLK/scratch-www/issues/2584

### Changes:

Adds a "View all" link at the top of the list of remixes on the project page

On Safari:
image

On Chrome:
image

/cc: @carljbowman @kathymakes

### CODE REVIEW

**Comment by carljbowman** [comment]
@benjiwheeler - Did you test with some different languages? Overall this seems good, but a little worried about how this will wrap with longer text. This also feels like something we could circle back on and fine tune.

**Comment by thisandagain** [comment]
@benjiwheeler Sorry I didn't include this in the scope sooner, but can we add this to the studios listing as well? Links to studio listing: https://scratch.mit.edu/projects/[id]/studios/

**Comment by benjiwheeler** [comment]
@carljbowman No I didn't, will test!

**Comment by benjiwheeler** [comment]
@thisandagain Added handling for studios list:

image

result of clicking:
image

**Pull request merged**
