### PR TITLE
Fix gh-357: Splash - Initial value of project count is arbitrary

### PR DESCRIPTION
**Pull request by TheGrits**
Updated the number with a more recent number, I wasn't sure if using a string like "Loading..." would damage anything.

Temporary fix for #357

Also added a comment about the project count, but that doesn't change much. :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by TheGrits** [comment]
If wanted, I could easily change the value to a string. Please let me know what you think.

**Comment by mewtaylor** [comment]
@TheGrits thanks for this, and sorry for the delay – I personally would totally be interested to see if you had any ideas for the "blank" state. Do you have any interest in doing another PR that does something more along those lines?

Another idea that comes to mind, on top of the one you mentioned, would be displaying "millions of" while the string is being loaded, or "many".

**Comment by TheGrits** [comment]
@mewtaylor My comment on Scratch was about my other PR, but this needs to be discussed too I guess. :stuck_out_tongue: 

I like the idea of using "millions of", something like "over 13 million" would work as well.

**Comment by mewtaylor** [comment]
@TheGrits ah gotcha – I'll take a look at that one now too :). And yeah, I think that if we're going to fix #357 it might make sense to do something that's more "blank" state while we're at it, if you wanna change this PR to do something like that. 

@carljbowman @kaschm would be interested to hear what you think about the default state (i.e. before we retrieve the actual number of projects from the api). Ideas include:
* Display "**over 13 million** projects shared..."
* Display "**millions of** projects shared..."
* Display "Loading..." instead of the whole string

**Comment by TheGrits** [comment]
@mewtaylor Ok, I changed it to "over 13 million". The only reason the checks are failing on the last PR update is because of the problem resolved by #361

**Comment by mewtaylor** [comment]
@TheGrits awesome thanks! I'm going to wait to hear back from the others for confirmation that the text works before reviewing to make sure that's the text we want :).

**Comment by mewtaylor** [comment]
@TheGrits looks good after the review of the text. Thanks!

**Pull request merged**
