### PR TITLE
Fix issue 1195 registration gender tabbing

### LINKED ISSUE #1195: Teacher registration gender options not accessible from keyboard
A user should be able to use tab to focus each of the gender radio buttons and select them from their keyboard. Currently these radio buttons are skipped while tabbing.

### PR DESCRIPTION
**Pull request by Petroochio**
Resolves #1195
Add focus highlight scss for radio buttons on demographic registration step.

### CODE REVIEW

**Comment by thisandagain** [comment]
Thanks @Petroochio! We'll take a look soon.

**Comment by mewtaylor** [comment]
@Petroochio is this your first PR on this repo, btw?

**Comment by Petroochio** [comment]
@mewtaylor Yes it is

**Comment by mewtaylor** [comment]
@Petroochio awesome :)
confetti-horn-emoji

**Comment by mewtaylor** [comment]
On Chrome 60, Mac OSX 10.12:
* Hitting `Tab` after being focused on `birth year` switches the focus to the first gender radio button
* Hitting an arrow key, while focused on the first gender radio button, will select different gender button choices
* Hitting `Tab` after selecting the input box gender radio button option changes the focus to that gender radio button's input field
* Hitting `Tab` while being focused on the gender radio buttons switches focus to the Country section

This seems consistent with the behavior we want, and now focus shows up for radio buttons, which fixes the highlighting issue on production

**Pull request merged**
