### PR TITLE
Donate Banner Update

### PR DESCRIPTION
**Pull request by kchadha**
### Changes:

Set up donate banner button with analytics. Remove end time for donate banner as per conversations offline.

### Test Coverage:

Tested locally with changing date & time on my computer and using the Google Analytics Debugger chrome extension.

### CODE REVIEW

**Comment by kchadha** [comment]
P.S. Thanks @rschamp for sending the GA docs!

**Review by rschamp — APPROVED** [review]

**Comment by jeffalo** [comment]
perhaps with the all the extra traffic to the donation page, this should be fixed?
image

it's asking for a scratcher's email address, which is against the community guidelines (under "Keep personal info private"). perhaps it should be changed to just a scratcher's username?

**Comment by GrahamSH-LLK** [comment]
> perhaps with the all the extra traffic to the donation page, this should be fixed?
> 
> it's asking for a scratcher's email address, which is against the community guidelines (under "Keep personal info private"). perhaps it should be changed to just a scratcher's username?

I'm not sure... It might be for parents who are donating for their children?

**Comment by Marc92020** [comment]
> > perhaps with the all the extra traffic to the donation page, this should be fixed?
> > it's asking for a scratcher's email address, which is against the community guidelines (under "Keep personal info private"). perhaps it should be changed to just a scratcher's username?
> 
> I'm not sure... It might be for parents who are donating for their children?

But if its not than this feature is impossible to use unless you somehow find their email.

**Comment by kchadha** [comment]
Closing in favor of #5434 which is the hotfix version of this PR.

**Pull request closed without merging**
