### PR TITLE
CE-296: Fix color contrast on project page icons

### LINKED ISSUE #7255: The color contrast for the remix, view, love, and favorites icons in the projects page is not in line with WCAG standards for color contrast.
### Where To Find Bug
`/projects`

### Expected Behaviour
People with low vision should be able to see the icons in grayscale properly.

### Actual Behaviour
The icons in grayscale are not WCAG compliant and, thus, are difficult for people with low vision to see.

### Steps To Reproduce

- Open https://scratch.mit.edu/ in any browser on your computer
- Click on any project
- Notice the show, remix, love, and favorite icons under the project picture.

### System Details
macOs Ventura, Chrome Browser, VoiceOver (AT)

### PR DESCRIPTION
**Pull request by Paul-Clue**
### Description:

The color contrast for the remix, views, favorite, and love icons is not up to WCAG standard. Resolves #7255.

### Test Cases:
I could not test these changes because I could not get the projects page to run locally. Hopefully, the reviewer of this pull request will be able to test these changes.

### CODE REVIEW

**Comment by Paul-Clue** [comment]
Can @chrisgarrity or any other reviewer from the scratch team review this pull request when time permits.

**Comment by DNin01** [comment]
This PR will conflict with https://github.com/LLK/scratch-www/pull/7264 since the love and the favorite icons are modified by both of them. You might have to just change the remix and view icons for now.

**Comment by Paul-Clue** [comment]
I make the changes.

**Comment by benjiwheeler** [comment]
Closing this as a duplicate of https://github.com/LLK/scratch-www/pull/7264

**Pull request closed without merging**
