### PR TITLE
Add "FloralSunset" to Credits Page

### LINKED ISSUE #4541: Update credits page
Please add Cindy (https://scratch.mit.edu/users/floralsunset) to the [Credits page](https://scratch.mit.edu/credits)!

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
### Resolves:

Resolves #4541 
### Changes:

Adds new scratchteam member.

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
Believe it or not, my 1st PR to this repo was the exact same thing!

**Comment by GrahamSH-LLK** [comment]
Believe it or not, my 1st PR to this repo was the exact same thing! //cc @benjiwheeler

**Comment by GrahamSH-LLK** [comment]
@benjiwheeler Can you review?

**Comment by benjiwheeler** [comment]
@GrahamSH-LLK Sorry for the delay! One change to suggest -- I think 'Cindy' should be alphabetized after all the 'Ch' names

**Comment by GrahamSH-LLK** [comment]
> @GrahamSH-LLK Sorry for the delay! One change to suggest -- I think 'Cindy' should be alphabetized after all the 'Ch' names

Okay! I'll fix that now!

**Comment by GrahamSH-LLK** [comment]
@benjiwheeler Done!

**Comment by benjiwheeler** [comment]
Thanks, @GrahamSH-LLK!

**Pull request merged**
