### PR TITLE
Fix gh-930: Update requirement string

### LINKED ISSUE #930: Update wedo page to include Windows 10
scratch.mit.edu/wedo should now include language around compatibility with Win 10: 

The LEGO WeDo 2.0 extension is currently only available for Mac OSX. We plan to release a Windows version later in 2016.

update to:

The LEGO WeDo 2.0 extension is available for Mac OSX and Windows 10+

also update the download text and link:

1. Install Device Manager

The Device Manager lets you connect WeDo 2.0 to Scratch using Bluetooth 

**Download for Mac OSX** [existing link]
**Download for Win 10+** [needs link @cwillisf ]

### PR DESCRIPTION
**Pull request by TheGrits**
Should fix #930

### CODE REVIEW

**Comment by TheGrits** [comment]
@mewtaylor @thisandagain @rschamp

**Comment by jwzimmer** [comment]
@mewtaylor The Windows Device Manager is not going to be deployed in Oct 20 milestone, but this change is up on Production already. Can we revert it, since it's misleading for users?

**Comment by jwzimmer** [comment]
Discussed with @mewtaylor, we can roll back this change in the deploy on Monday.
/cc @kaschm & @cwillisf

**Comment by kaschm** [comment]
Thanks @mewtaylor @jwzimmer

**Comment by jwzimmer** [comment]
Now on Staging, the old version ( 👍 ):
screen shot 2016-10-28 at 9 44 57 am

**Comment by mewtaylor** [comment]
@kaschm sorry about that!

**Pull request merged**
