### PR TITLE
Fix gh-940: missing translations

### PR DESCRIPTION
**Pull request by chrisgarrity**
Updated the build-locales script to handle duplicate strings. 

You can spot check the output by looking in the intl directory. 

about.intl.js: the key 'about.whoUsesScratch' should be translated in many languages. 
hoc.intl.js: the key 'hoc.tipsAnimateYourNameTitle' should be in languages other than English

### CODE REVIEW

**Comment by mewtaylor** [comment]
Related to #961

**Comment by jwzimmer** [comment]
### Testing, Chrome 53, Mac OS X El Capitan

- [ ] **About page** 
  - 'Who uses Scratch' and 'Scratch in Schools' from the italian translation
- [ ] **"Projects curated by" on the splash page**
- [ ] **The words in the graphics on the statistics page?**
  - Not sure if should be translated: https://github.com/LLK/scratchr2/issues/4134
- [ ] **The Credits page?**
  - https://scratch.mit.edu/info/credits/
- [ ] In preparation for EU Code Week (Oct. 15), noting that a couple of the strings are not included in the translation on the HOC page in Italian, or Norwegian:
  - Animate Your Name, ANIMATE YOUR NAME (in two places), and Dance, Dance, Dance are showing up in English on the HOC page
- [ ] Noticed this with Portuguese + Teacher Registration today in Production. The validation string seems to be translated sometimes but not always ("this field is required")
  - See Organization step

**Comment by chrisgarrity** [comment]
The statistics page is actually in scratchr2 not www, so those won't be translated. 
The credits page was completely untranslated rather than a few untranslated strings, so I opened a separate issue #959 to decide whether it should be translated.

**Comment by jwzimmer** [comment]
@chrisgarrity Okay, thanks for explaining 👍

**Comment by jwzimmer** [comment]
@mewtaylor & @chrisgarrity I checked this PR pretty narrowly, just looking to see if it fixed the specific issues raised by @ntlrsk and in #940. Let me know if you think it should have more intense scrutiny. Thanks.

**Comment by chrisgarrity** [comment]
@jwzimmer Did the validation messages get fixed? I wasn't sure those where the same problem. If not we should probably open a new issue for them as it wasn't a symptom of the same bug.

**Comment by jwzimmer** [comment]
@chrisgarrity I opened a new issue for it as https://github.com/LLK/scratch-www/issues/966. : )

**Pull request merged**
